# Generated by Django 5.0.6 on 2025-09-04 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_assignment_lesson_alter_quiz_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='completion_status',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='forum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Video', 'Video'), ('Text', 'Text'), ('PDF', 'PDF')], max_length=10)),
                ('value', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms_app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
    ]
