# Generated by Django 5.0.6 on 2025-09-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms_app.forum'),
        ),
    ]
